homepage:
    path: /
    controller: App\Controller\Ecorp\HomepageController::home

connect_google_start:
    path: /connect/google
    controller: App\Controller\Ecorp\GoogleController::connect

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\Ecorp\GoogleController::connectCheck

logout:
  path: /logout
  methods: GET

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"