knpu_oauth2_client:
    clients:
        google:
            type: google
#            client_id: '%env(GOOGLE_ID)%'
            client_id: 836716831376-np3ih13sbt21j6qih52m9iclivv012dm.apps.googleusercontent.com
#            client_secret: '%env(GOOGLE_ID)%'
            client_secret: 5TdwJ061RP4ffDId2V-xZrXT
            redirect_route: connect_google_check
            redirect_params: {}
